<?php

use App\Accessories;
use Illuminate\Database\Seeder;

class AccessoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Accessories::truncate();
        $datas = array(
            array('access_name' => 'PC-170600901142','unit' => 'Set'),
            array('access_name' => 'สาย UTP CAT 6(300M) Outdoor','unit' => 'Box'),
            array('access_name' => 'RJ45 Cat6MODULAR PLUG(10PCS/PKG)','unit' => 'PKG'),
            array('access_name' => 'NB HP 901108(conference)','unit' => 'SET'),
            array('access_name' => 'สาย UTP CAT 5E(300M) Indoor','unit' => 'Box'),
            array('access_name' => 'FlashDrive 8GB Apacer','unit' => 'Pc'),
            array('access_name' => 'Notebook Dell 901106','unit' => 'Pc'),
            array('access_name' => 'พัดลม 4 inch single GERMANY','unit' => 'ตัว'),
            array('access_name' => 'FlashDrive 8GB Kingston','unit' => 'Pc'),
            array('access_name' => 'Notebook Asus 900717','unit' => 'Pc'),
            array('access_name' => 'เครื่องสำรองไฟ(UPS)500VA','unit' => 'Pc'),
            array('access_name' => 'PoE Adapter 48V','unit' => 'Pc'),
            array('access_name' => 'Boot Cat6 10 ชิ้น','unit' => 'ถุง'),
            array('access_name' => 'Battery NB Dell 5437','unit' => 'Pc'),
            array('access_name' => 'ประแจ 6 เหลี่ยม','unit' => 'SET'),
            array('access_name' => 'USB3.5 SATA/IDE','unit' => 'Pc'),
            array('access_name' => 'USB2.5 SATA','unit' => 'Pc'),
            array('access_name' => 'เครื่องดูดฝุ่น','unit' => 'Pc'),
            array('access_name' => 'ปลั๊กพ่วง 4 ช่อง 5 เมตร','unit' => 'Pc'),
            array('access_name' => 'ตัวล็อคโน๊ตบุ๊ค','unit' => 'เส้น'),
            array('access_name' => 'สาย HDMI 1.5 เมตร','unit' => 'เส้น'),
            array('access_name' => 'สาย HDMI 5 เมตร','unit' => 'เส้น'),
            array('access_name' => 'สาย VGA MM 5 เมตร','unit' => 'เส้น'),
            array('access_name' => 'สาย VGA MM 10 เมตร','unit' => 'เส้น'),
            array('access_name' => 'คีย์บอร์ด USB','unit' => 'Pc'),
            array('access_name' => 'เม้าส์สาย','unit' => 'Pc'),
            array('access_name' => 'Power Supply ใหญ่','unit' => 'Pc'),
            array('access_name' => 'Power Supply เล็ก','unit' => 'Pc'),
            array('access_name' => 'USB Wifi','unit' => 'Pc'),
            array('access_name' => 'FlashDrive 16GB Kingston','unit' => 'Pc'),
            array('access_name' => 'สาย HDMI to VGA','unit' => 'Pc'),
            array('access_name' => 'แผ่นรองเม้าส์','unit' => 'Pc'),
            array('access_name' => 'เม้าส์ไร้สาย','unit' => 'Pc'),
            array('access_name' => 'Adapter NB All in one','unit' => 'Pc'),
            array('access_name' => 'Adapter NB Asus','unit' => 'Pc'),
            array('access_name' => 'การ์ดแลน PCI','unit' => 'Pc'),
            array('access_name' => 'การ์ดไวเลสสั้น','unit' => 'Pc'),
            array('access_name' => 'การ์ดไวเลสยาว','unit' => 'Pc'),
            array('access_name' => 'ปลั้ก Convert','unit' => 'Pc'),
            array('access_name' => 'Hard Disk 2.5','unit' => 'Pc'),
            array('access_name' => 'โมดูล SFP','unit' => 'Pc'),
            array('access_name' => 'ซองใส่ซีดี','unit' => 'ซอง'),
            array('access_name' => 'RJ45 Cat5 100 ชิ้น','unit' => 'ถุง'),
            array('access_name' => 'CD External NB','unit' => 'Pc'),
            array('access_name' => 'CD External PC','unit' => 'Pc'),
            array('access_name' => 'HDD For NAS 4TB','unit' => 'Pc'),
            array('access_name' => 'HDD For NAS 2TB','unit' => 'Pc'),
            array('access_name' => 'HDD For CCTV 4TB','unit' => 'Pc'),
            array('access_name' => 'HDD For PC 1TB','unit' => 'Pc'),
            array('access_name' => 'แผ่น CD-R','unit' => 'แผ่น'),
            array('access_name' => 'แผ่น DVD-R','unit' => 'แผ่น'),
            array('access_name' => 'หมึก HP Black45','unit' => 'Pc'),
            array('access_name' => 'หมึก HP Black60','unit' => 'Pc'),
            array('access_name' => 'หมึก HP Black94','unit' => 'Pc'),
            array('access_name' => 'Numpad Targus','unit' => 'Pc'),
            array('access_name' => 'Gel Cleaner','unit' => 'Pc'),
            array('access_name' => 'Ram NB 4GB/1600','unit' => 'Pc'),
            array('access_name' => 'หมึก EPSON T1031 4สี','unit' => 'SET'),
            array('access_name' => 'Android box','unit' => 'Pc'),
            array('access_name' => 'ถ่าน BIOS CR2032','unit' => 'Pc'),
            array('access_name' => 'หัวปริ้นเตอร์ EPSON','unit' => 'Pc'),
            array('access_name' => 'หัวปริ้นเตอร์ OKI','unit' => 'Pc'),
            array('access_name' => 'Battery NB G400','unit' => 'Pc'),
            array('access_name' => 'Battery NB Asus X44H, K53','unit' => 'Pc'),
            array('access_name' => 'Battery NB Asus X450C','unit' => 'Pc'),
            array('access_name' => 'UniFi MESH','unit' => 'Pc'),
            array('access_name' => 'Wireless Router D-Link','unit' => 'Pc'),
            array('access_name' => 'USB HUB 7 Slot','unit' => 'Pc'),
            array('access_name' => 'สาย USB Printer','unit' => 'เส้น'),
            array('access_name' => 'Battery PDA','unit' => 'Pc'),
            array('access_name' => 'Adapter PDA','unit' => 'Pc'),
            array('access_name' => 'เครื่องเป่าลม Bosch','unit' => 'Pc'),
            array('access_name' => 'IP Phone','unit' => 'Pc'),
            array('access_name' => 'Switch TP-Link 8Port (4PoE)','unit' => 'Pc'),
            array('access_name' => 'ตลับหมึก Ribbon LQ-2090','unit' => 'Pc'),
            array('access_name' => 'ตลับหมึก Ribbon Fujitsu-DL6400','unit' => 'Pc'),
            array('access_name' => 'ตลับหมึก Ribbon LQ-2180,2080,2190','unit' => 'Pc'),
            array('access_name' => 'Refill Fujitsu 6400','unit' => 'Pc'),
            array('access_name' => 'Refill EPSON 2170,2180','unit' => 'Pc'),
            array('access_name' => 'Refill EPSON 2090','unit' => 'Pc'),
            array('access_name' => 'Refill EPSON 1070,1170','unit' => 'Pc'),
            array('access_name' => 'ตลับหมึก Oki ML-590,591','unit' => 'Pc'),
            array('access_name' => 'ตลับหมึก Oki 390,391','unit' => 'Pc'),
            array('access_name' => 'ตลับหมึก Oki 590,591','unit' => 'Pc'),
            array('access_name' => 'Toner HP CB436','unit' => 'Pc'),
            array('access_name' => 'Toner HP 92A','unit' => 'Pc'),
            array('access_name' => 'Toner HP 12A','unit' => 'Pc'),
            array('access_name' => 'Toner HP 80A','unit' => 'Pc'),
            array('access_name' => 'Toner Brother TN-2150','unit' => 'Pc'),
            array('access_name' => 'Toner Drum DR-2150','unit' => 'Pc'),
            array('access_name' => 'Toner Brother DR-2125','unit' => 'Pc'),
            array('access_name' => 'Toner Brother TN-2025','unit' => 'Pc'),
            array('access_name' => 'ตลับหมึก Laser Q-2613A','unit' => 'Pc'),
            array('access_name' => 'ตลับหมึก Laser Q-7551X','unit' => 'Pc'),
            array('access_name' => 'Toner Brother DR-2025','unit' => 'Pc'),
            array('access_name' => 'กระเป๋าโน๊ตบุ๊ค (เป้)','unit' => 'Pc'),
            array('access_name' => 'กระเป๋าโน๊ตบุ๊ค (HP)','unit' => 'Pc'),
            array('access_name' => 'กระเป๋าโน๊ตบุ๊ค (Acer)','unit' => 'Pc'),
            array('access_name' => 'NB HP 901117','unit' => 'SET'),
            array('access_name' => 'NB HP 901122','unit' => 'SET'),
            array('access_name' => 'NB Acer 901020 (กระเป๋า Asus)','unit' => 'SET'),
            array('access_name' => 'NB Acer 900965','unit' => 'SET'),
            array('access_name' => 'Wireless Presentation Gateway','unit' => 'SET'),
            array('access_name' => 'Ram PC 4GB UNB PC3-12800 CL11(1.35V)','unit' => 'Pc'),
            array('access_name' => 'Ram PC 4GB UNB PC3-12800U','unit' => 'Pc'),
            array('access_name' => 'Ram PC 2GB/800 D2(Blackberry)','unit' => 'Pc'),
            array('access_name' => 'Ram PC 1GB/400 D1(Blackberry)','unit' => 'Pc'),
            array('access_name' => 'Ram PC 512MB/133 SD(Blackberry)','unit' => 'Pc'),
            array('access_name' => 'Ram NB 4GB PC3-12800 CL11(KVR16S11S8/4)','unit' => 'Pc'),
            array('access_name' => 'Ram NB 512MB1Rx8PC2-5300S','unit' => 'Pc'),
            array('access_name' => 'Ram NB 512MB2Rx16PC2-4200S','unit' => 'Pc'),
            array('access_name' => 'Ram NB 2GB1Rx8PC3-10600S','unit' => 'Pc'),
            array('access_name' => 'Ram Server 128MB DDR PC2100 CL2.5','unit' => 'Pc'),
            array('access_name' => 'Ram Server KTH-MLG4/4GB KIT OF 2 1.8V','unit' => 'Pc'),
            array('access_name' => 'กระดาษ A4','unit' => 'ริม'),
            array('access_name' => 'Battery UPS 12V7.2Ah','unit' => 'Pc'),
            array('access_name' => 'D-LINK DGS-1016D','unit' => 'Pc'),
            array('access_name' => 'D-LINK DGS-1024D','unit' => 'Pc'),
            array('access_name' => 'EdgeSwitch8xp','unit' => 'Pc'),
            array('access_name' => 'PCI to Series 2 port controller card','unit' => 'Pc'),
            array('access_name' => 'สาย UTP CAT 6(300M) Indoor','unit' => 'BOX'),
            array('access_name' => 'สาย HDMI 20 เมตร','unit' => 'เส้น')
        );
        foreach ($datas as $key => $value) {
            Accessories::create($value);
        }
    }
}
