<?php

use App\Models\Department;
use Illuminate\Database\Seeder;

class DepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $departments = [
            ['id' => 1, 'name' => 'Management Administration'],
            ['id' => 2, 'name' => 'President'],
            ['id' => 3, 'name' => 'Strategy & Operation'],
            ['id' => 4, 'name' => 'RICA'],
            ['id' => 5, 'name' => 'Legal'],
            ['id' => 6, 'name' => 'IT'],
            ['id' => 7, 'name' => 'Operation'],
            ['id' => 8, 'name' => 'ADM Management'],
            ['id' => 9, 'name' => 'Human Resource and Genaral Admin'],
            ['id' => 10, 'name' => 'Human Resource'],
            ['id' => 11, 'name' => 'General Admin'],
            ['id' => 12, 'name' => 'SHE & ISO'],
            ['id' => 13, 'name' => 'Finance & Accounting'],
            ['id' => 14, 'name' => 'Finance Planning Analysis'],
            ['id' => 15, 'name' => 'Accounting'],
            ['id' => 16, 'name' => 'A/R & Credit Management'],
            ['id' => 17, 'name' => 'Cash Management'],
            ['id' => 18, 'name' => 'Costing'],
            ['id' => 19, 'name' => 'Marketing'],
            ['id' => 20, 'name' => 'Sales RF'],
            ['id' => 21, 'name' => 'Sales AC'],
            ['id' => 22, 'name' => 'Order Coordinator'],
            ['id' => 23, 'name' => 'Customer Service'],
            ['id' => 24, 'name' => 'Supply Chain Management'],
            ['id' => 25, 'name' => 'Vendor Management & Sourcing'],
            ['id' => 26, 'name' => 'Cost Management'],
            ['id' => 27, 'name' => 'Import & Export'],
            ['id' => 28, 'name' => 'Order Management'],
            ['id' => 29, 'name' => 'Indirect Procurement'],
            ['id' => 30, 'name' => 'Utility'],
            ['id' => 31, 'name' => 'Indirect Production'],
            ['id' => 32, 'name' => 'Support Platform RF'],
            ['id' => 33, 'name' => 'Admin Support Platform RF'],
            ['id' => 34, 'name' => 'In House Part Production'],
            ['id' => 35, 'name' => 'Door Liner Forming (TF)'],
            ['id' => 36, 'name' => 'Inner box Forming (TF)'],
            ['id' => 37, 'name' => 'Metal Coat (MC)'],
            ['id' => 38, 'name' => 'Door Bend A'],
            ['id' => 39, 'name' => 'Door Foam A'],
            ['id' => 40, 'name' => 'Production Line A'],
            ['id' => 41, 'name' => 'Inner Box A'],
            ['id' => 42, 'name' => 'Roll A'],
            ['id' => 43, 'name' => 'Cab pre-assy A'],
            ['id' => 44, 'name' => 'Cabinet PU Foam A'],
            ['id' => 45, 'name' => 'Assembly A'],
            ['id' => 46, 'name' => 'System ass`y A'],
            ['id' => 47, 'name' => 'Vacuum A'],
            ['id' => 48, 'name' => 'Final A'],
            ['id' => 49, 'name' => 'Packing A'],
            ['id' => 50, 'name' => 'MIZ & Costing A'],
            ['id' => 51, 'name' => 'Production Line B'],
            ['id' => 52, 'name' => 'Inner Box B'],
            ['id' => 53, 'name' => 'Roll B'],
            ['id' => 54, 'name' => 'Cab pre-assy B'],
            ['id' => 55, 'name' => 'Cabinet PU Foam B'],
            ['id' => 56, 'name' => 'Assembly B'],
            ['id' => 57, 'name' => 'System ass`y B'],
            ['id' => 58, 'name' => 'Vacuum B'],
            ['id' => 59, 'name' => 'Final B'],
            ['id' => 60, 'name' => 'Packing B'],
            ['id' => 61, 'name' => 'MIZ & Costing B'],
            ['id' => 62, 'name' => 'Spare - B'],
            ['id' => 63, 'name' => 'Production Support RF'],
            ['id' => 64, 'name' => 'Admin -Production Support RF'],
            ['id' => 65, 'name' => 'RM Warehouse (RF)'],
            ['id' => 66, 'name' => 'FG Warehouse (RF)'],
            ['id' => 67, 'name' => 'Spare Part Warehouse (RF)'],
            ['id' => 68, 'name' => 'Quality AC'],
            ['id' => 69, 'name' => 'AC PQC'],
            ['id' => 70, 'name' => 'IQC (SAC)'],
            ['id' => 71, 'name' => 'OQC (SAC)'],
            ['id' => 72, 'name' => 'AC- R&D'],
            ['id' => 73, 'name' => 'R&D AC'],
            ['id' => 74, 'name' => 'Bom AC'],
            ['id' => 75, 'name' => 'E&M AC'],
            ['id' => 77, 'name' => 'Spare - A'],
            ['id' => 78, 'name' => 'Spare - A'],
            ['id' => 79, 'name' => 'Spare - '],
            ['id' => 80, 'name' => 'Spare - AC-IDU'],
            ['id' => 81, 'name' => 'Spare - RAC-ODU'],
            ['id' => 82, 'name' => 'Spare - CAC-ODU'],
            ['id' => 83, 'name' => 'Spare - WAC'],
            ['id' => 84, 'name' => 'RF Procurement'],
            ['id' => 85, 'name' => 'Subcontractor '],
            ['id' => 86, 'name' => 'FUL FILL'],
            ['id' => 87, 'name' => 'GET'],
            ['id' => 88, 'name' => 'Door Bend B'],
            ['id' => 89, 'name' => 'Door Foam B'],
            ['id' => 90, 'name' => 'Corprate Culture'],
            ['id' => 91, 'name' => 'Direct Production'],
            ['id' => 92, 'name' => 'RF Haier'],
            ['id' => 93, 'name' => 'PQC (RF) A'],
            ['id' => 94, 'name' => 'Production Planning A'],
            ['id' => 95, 'name' => 'Maintenance A'],
            ['id' => 96, 'name' => 'R&D/ET A'],
            ['id' => 97, 'name' => 'Production Platform  RF'],
            ['id' => 98, 'name' => 'Maintenance IH'],
            ['id' => 99, 'name' => 'Machine Engineering IH'],
            ['id' => 100, 'name' => 'PQC IH'],
            ['id' => 101, 'name' => 'R&D/ET IH'],
            ['id' => 102, 'name' => 'RF AQUA'],
            ['id' => 103, 'name' => 'PQC (RF) B'],
            ['id' => 104, 'name' => 'Production Planning B'],
            ['id' => 105, 'name' => 'Maintenance B'],
            ['id' => 106, 'name' => 'R&D/ET B'],
            ['id' => 107, 'name' => 'Technical Platform'],
            ['id' => 108, 'name' => 'E&M (RF)'],
            ['id' => 109, 'name' => 'Admin E&M'],
            ['id' => 110, 'name' => 'Mechanical Engineering'],
            ['id' => 111, 'name' => 'Preventive Maintenance'],
            ['id' => 112, 'name' => 'Store'],
            ['id' => 113, 'name' => 'R&D (RF)'],
            ['id' => 114, 'name' => 'Admin R&D'],
            ['id' => 115, 'name' => 'BOM RF'],
            ['id' => 116, 'name' => 'Product Development RF'],
            ['id' => 117, 'name' => 'Quality RF'],
            ['id' => 118, 'name' => 'IQC (RF)'],
            ['id' => 119, 'name' => 'OQC (RF)'],
            ['id' => 120, 'name' => 'Repainting RF'],
            ['id' => 121, 'name' => 'Support Platform AC'],
            ['id' => 122, 'name' => 'ADM- Support Platform AC'],
            ['id' => 123, 'name' => 'SAC Micro'],
            ['id' => 124, 'name' => 'ADM SAC'],
            ['id' => 125, 'name' => 'Production Line SAC'],
            ['id' => 126, 'name' => 'Indoor 1'],
            ['id' => 127, 'name' => 'Indoor 2'],
            ['id' => 128, 'name' => 'Outdoor'],
            ['id' => 129, 'name' => 'PQC SAC'],
            ['id' => 130, 'name' => 'PQC (SAC)-Indoor 1'],
            ['id' => 131, 'name' => 'PQC (SAC)-Indoor 2'],
            ['id' => 132, 'name' => 'PQC (SAC)-Outdoor'],
            ['id' => 133, 'name' => 'Production Planning SAC'],
            ['id' => 134, 'name' => 'Production Platform  AC'],
            ['id' => 135, 'name' => 'Production Support AC'],
            ['id' => 136, 'name' => 'FG Warehouse (SAC)'],
            ['id' => 137, 'name' => 'RM Warehouse (SAC)'],
            ['id' => 138, 'name' => 'Purchasing AC'],
            ['id' => 139, 'name' => 'WAC Micro'],
            ['id' => 140, 'name' => 'Admin-WAC'],
            ['id' => 141, 'name' => 'EVAP & Condenser Line  WAC'],
            ['id' => 142, 'name' => 'Production Line WAC'],
            ['id' => 143, 'name' => 'PQC WAC'],
            ['id' => 144, 'name' => 'Production Planning WAC'],
            ['id' => 145, 'name' => 'Technical Platform AC'],
            ['id' => 146, 'name' => 'IQC (WAC)'],
            ['id' => 147, 'name' => 'OQC (WAC)'],
            ['id' => 148, 'name' => 'Spare - Door'],
            ['id' => 149, 'name' => 'AC'],
            ['id' => 150, 'name' => 'Purchasing (RF)'],
            ['id' => 151, 'name' => 'Inner Box B (VZ)'],
            ['id' => 152, 'name' => 'CAC'],
            ['id' => 153, 'name' => 'Spare Inner Box A'],
            ['id' => 154, 'name' => 'Spare Roll A'],
            ['id' => 155, 'name' => 'Spare Cab pre-assy A'],
            ['id' => 156, 'name' => 'Spare PU Foam A'],
            ['id' => 157, 'name' => 'Spare Assembly A'],
            ['id' => 158, 'name' => 'Spare System ass`y A'],
            ['id' => 159, 'name' => 'Spare Vacuum A'],
            ['id' => 160, 'name' => 'Spare Final A'],
            ['id' => 161, 'name' => 'Spare Packing A'],
            ['id' => 162, 'name' => 'Spare Door Bend A'],
            ['id' => 163, 'name' => 'Spare Door Foam A'],
            ['id' => 164, 'name' => 'Spare Inner Box B'],
            ['id' => 165, 'name' => 'Spare Roll B'],
            ['id' => 166, 'name' => 'Spare Cab pre-assy B'],
            ['id' => 167, 'name' => 'Spare PU Foam B'],
            ['id' => 168, 'name' => 'Spare Assembly B'],
            ['id' => 169, 'name' => 'Spare System ass`y B'],
            ['id' => 170, 'name' => 'Spare Vacuum B'],
            ['id' => 171, 'name' => 'Spare Final B'],
            ['id' => 172, 'name' => 'Spare Packing B'],
            ['id' => 173, 'name' => 'Spare Door Bend B'],
            ['id' => 174, 'name' => 'Spare Door Foam B'],
            ['id' => 175, 'name' => 'Spare PQC(A)'],
            ['id' => 176, 'name' => 'Spare PQC(B)'],
            ['id' => 177, 'name' => 'Spare Production '],
            ['id' => 178, 'name' => 'Production Support RF'],
            ['id' => 180, 'name' => 'Spare SAC'],
            ['id' => 181, 'name' => 'Spare WAC'],
            ['id' => 182, 'name' => 'PQC CAC'],
            ['id' => 183, 'name' => 'ADM SAC'],
            ['id' => 184, 'name' => 'FG Warehouse (WAC)'],
            ['id' => 185, 'name' => 'RM Warehouse (WAC)'],
            ['id' => 186, 'name' => 'WAC PCB Assembly Line'],
            ['id' => 187, 'name' => 'Spare HR'],

        ];
        foreach ($departments as $key => $value) {
            Department::firstOrCreate($value);
        }
    }
}
